# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.parser_controller:
        class: AppBundle\Controller\ParserController
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
        calls:
            - [setContainer, ["@service_container"]]
    app.execute_controller:
        class: AppBundle\Controller\ExecuteController
        calls:
            - [setContainer, ["@service_container"]]
    app.soccer_controller:
            class: AppBundle\Controller\SoccerController
            calls:
                - [setContainer, ["@service_container"]]